name: Build and Publish Docker Image

on:
  push:
    branches:
      - RELEASE

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      PROM_VERSION: "3.5.0"
      ARCH: "amd64"
      OS: "linux"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build \
            --build-arg PROM_VERSION=$PROM_VERSION \
            --build-arg ARCH=$ARCH \
            --build-arg OS=$OS \
            -t oleksandmukas/task1-prom:$PROM_VERSION .
          docker tag oleksandmukas/task1-prom:$PROM_VERSION oleksandmukas/task1-prom:RELEASE

      - name: Push Docker images
        run: |
          docker push oleksandmukas/task1-prom:$PROM_VERSION
          docker push oleksandmukas/task1-prom:RELEASE
